### ISSUE TITLE
After latest upgrade PLEX fails to start.

### ISSUE THREAD

**Issue by ZeDima** [mstinaff/PMS_Updater#67] opened 2023-08-07 11:19 UTC
After installing latest update PLEX fails to start. Manually triggering the update the following issue is displayed.

```
root@PLEX:/ # sh ./PMS_Updater.sh
Using URL https://plex.tv/api/downloads/5.json
Searching https://plex.tv/api/downloads/5.json for the FreeBSD download URL .....Segmentation fault
Could not find a FreeBSD download link on page https://plex.tv/api/downloads/5.json?channel=plexpass&X-Plex-Token=************
```

**Comment by visseroth** [comment] 2023-08-08 03:41
Getting the same thing.... Could not find a FreeBSD download link on page https://plex.tv/api/downloads/5.json?channel=plexpass&X-Plex-Token=Ms7w5J6Nyu8Rp9ws4BxM

**Comment by harvimt** [comment] 2023-08-08 04:53
I have no problems downloading the 1.32.6.7371-b6a09ad81-FreeBSD-amd64.tar.bz2 version of Plex, but the plexmediaserver service is failing to start.

I see:

```
Aug  7 21:38:25 plex-3 root[33549]: /usr/local/etc/rc.d/plexmediaserver: WARNING: failed to start plexmediaserver
```

in /var/log/messages and no other errors.

**Comment by visseroth** [comment] 2023-08-08 05:29
I tried a manual update and ended up with the same problem you have harvimt

**Comment by COnrust** [comment] 2023-08-08 10:02
I had the same, rolled back to another snapshot of my plex jail and it worked again. After running the pms_updater.sh again it once again failed to start. But then I noticed in my backup dir that there were 2 symlinks:

`libpython2.7.so -> /usr/local/share/plexmediaserver/lib/libpython27.so`

and 

`Plex_Media_Server -> /usr/local/share/plexmediaserver/Plex Media Server`

So when I added those again, it managed to start again. Hope this helps.

**Comment by ZeDima** [comment] 2023-08-08 10:12
Would the correct commands be:
```
ln -s libpython2.7.so /usr/local/share/plexmediaserver/lib/libpython27.so
ln -s Plex_Media_Server -> /usr/local/share/plexmediaserver/Plex Media Server
```

**Comment by COnrust** [comment] 2023-08-08 10:13
That is correct, depending on where you installed plex you should change your path ofc.

**Comment by ZeDima** [comment] 2023-08-08 11:44
It's installed in a separate jail as a plugin. TrueNAS-13.0-U5.3 and jail is 13.0-RELEASE-p13. I'm getting this for some reason:
```
root@PLEX:/ # ln -s libpython2.7.so /usr/local/share/plexmediaserver/lib/libpython27.so
ln: /usr/local/share/plexmediaserver/lib/libpython27.so: File exists
```

**Comment by COnrust** [comment] 2023-08-08 11:57
Ah I'm sorry, it should be the other way around:
`ln -s /usr/local/share/plexmediaserver/lib/libpython27.so libpython2.7.so
ln -s  /usr/local/share/plexmediaserver/Plex Media Server Plex_Media_Server`

run these in /user/local/share/plexmediaserver 

I also have it installed in a truenas jail as a plugin btw

**Comment by ZeDima** [comment] 2023-08-08 12:09
It looks like I was missing the Python one. Also I ran them in `/usr/local/share/plexmediaserver` and it didn't help unfortunately. 
![image](https://github.com/mstinaff/PMS_Updater/assets/49519829/4ce3df84-2ce8-49a1-bf5c-82a3615a01d7)

**Comment by ZeDima** [comment] 2023-08-08 12:27
I actually did. Shouldn't I do it? I mean the PMS_Updater script does restart the service anyway, doesen't it?
```
Aug  8 15:12:01 PLEX pkg[12101]: libunwind-20211201_2 installed
Aug  8 15:12:01 PLEX pkg[12101]: argp-standalone-1.5.0 installed
Aug  8 15:12:02 PLEX pkg[12101]: libogg-1.3.5,4 installed
Aug  8 15:12:03 PLEX pkg[12101]: p11-kit-0.24.1_2 installed
Aug  8 15:12:03 PLEX pkg[12101]: fontconfig-2.14.2,1 installed
Aug  8 15:12:04 PLEX pkg[12101]: libx264-0.164.3095 installed
Aug  8 15:12:04 PLEX pkg[12101]: libva-2.19.0 installed
Aug  8 15:12:05 PLEX pkg[12101]: aom-3.6.1 installed
Aug  8 15:12:06 PLEX pkg[12101]: gnutls-3.7.9 installed
Aug  8 15:12:06 PLEX pkg[12101]: webp-1.3.1_1 installed
Aug  8 15:12:07 PLEX pkg[12101]: libv4l-1.23.0_2 installed
Aug  8 15:12:08 PLEX pkg[12101]: lame-3.100_4 installed
Aug  8 15:12:08 PLEX pkg[12101]: libass-0.17.1_1 installed
Aug  8 15:12:09 PLEX pkg[12101]: x265-3.4_2 installed
Aug  8 15:12:09 PLEX pkg[12101]: opus-1.4 installed
Aug  8 15:12:10 PLEX pkg[12101]: libvorbis-1.3.7_2,3 installed
Aug  8 15:12:10 PLEX pkg[12101]: svt-av1-1.6.0 installed
Aug  8 15:12:11 PLEX pkg[12101]: libplacebo-6.292.0 installed
Aug  8 15:12:11 PLEX pkg[12101]: dav1d-1.2.1_1 installed
Aug  8 15:12:12 PLEX pkg[12101]: libvpx-1.13.0 installed
Aug  8 15:12:12 PLEX pkg[12101]: libvdpau-1.5 installed
Aug  8 15:12:14 PLEX pkg[12101]: ffmpeg-6.0_1,1 installed
Aug  8 15:13:50 PLEX syslogd: exiting on signal 15
Aug  8 15:13:55 PLEX syslogd: kernel boot file is /boot/kernel/kernel
Aug  8 15:13:55 PLEX root[13740]: /etc/rc: WARNING: failed to start plexmediaserver
root@PLEX:/var/log #
```

**Comment by ZeDima** [comment] 2023-08-08 12:36
Both are root|wheel.

**Comment by COnrust** [comment] 2023-08-08 12:48
I'm afraid I don't know what the issue is then. This is what solved it for me. Do you have any recent snapshots of your jail? Maybe rollback and start again from a working version

**Comment by ZeDima** [comment] 2023-08-08 12:50
Well it looks like running the "Update" from TrueNAS plugins menu restores the functionality and downgrades the version to a working one. Thank you for your time anyway tho. 
Hope the script gets updated in the near future and restores it's former glory =) !

**Comment by COnrust** [comment] 2023-08-08 12:51
np! Glad you found a workaround for now at least :) and ye let's hope so

**Comment by davidsch1992** [comment] 2023-08-09 22:50
Hello all,

For me it worked to manually update the plex server with an earlier version: 
`root@Plex:~ # ./PMS_Updater.sh -v -a -l ./<Path_to_the_local_installer_file>`

In my case: Path_to_the_local_file = 1.32.5.7349.8f4248874-FreeBSD-amd64.tar.bz2

**Comment by orrinwitt** [comment] 2023-08-10 02:14
I'm leaving a comment here to say I'm having the same problem as of this week too. 
Would I be wrong to say this script appears to be broken now? Like all of us here, I've loved having this script to keep my server on the latest version. If @mstinaff is no longer available to update/maintain it, is anyone with the right skills up for forking it or taking over? 
I wish I knew enough to be useful!

**Comment by harvimt** [comment] 2023-08-10 03:04
The script itself seems fine, the actual package from plex seems to be what's broken... the script can install the package, it's just that then it does not run.

There isn't an official TrueNAS plugin update for 1.32.6.7371-b6a09ad81 yet, they may add patches on top of what plex added.

**Comment by orrinwitt** [comment] 2023-08-12 14:18
So do we just wait for the next update and see if installing that package returns our servers to working condition?
I went ahead and installed the plugin as a backup in the meantime. Downgrading via snapshot rollback didn't work for me.

**Comment by MAGICCC** [comment] 2023-08-13 18:18
I assume plex broke something because it errors with a SIGSEGV. You can download PlexMediaServer-1.32.5.7349.8f4248874-FreeBSD-amd64.tar.bz2 and use the -l parameter to install it.

**Comment by ootagoo** [comment] 2023-08-17 02:58
[Looks like this is actually a Plex problem](https://forums.plex.tv/t/plexmediaserver-1-32-6-7371-broken-on-freebsd/849348/32) and not a PMS problem. Downgrade is necessary. You can do this from PMS:

`fetch https://downloads.plex.tv/plex-media-server-new/1.32.5.7349-8f4248874/freebsd/PlexMediaServer-1.32.5.7349-8f4248874-FreeBSD-amd64.tar.bz2
./PMS_Updater -l PlexMediaServer-1.32.5.7349-8f4248874-FreeBSD-amd64.tar.bz2`

We will just have to wait and see if they fix 1.32.6 for FreeBSD. Until then they should really remove the DL link..

**Comment by IrocDL** [comment] 2023-08-29 17:17
Has this been fixed? I still get the issue when I try to update using the script, and have to roll back to a snapshot to get Plex working again.

**Comment by MAGICCC** [comment] 2023-08-29 17:28
It's not that script issue, it's a Plex issue, nothing we can 'fix'

**Comment by IrocDL** [comment] 2023-08-29 17:30
I see. Is there a workaround?

**Comment by ZeDima** [comment] 2023-08-29 17:31
I think it is enough to just update/upgrade from the Plugin menu if you have installed it via plug-in menu.

**Comment by IrocDL** [comment] 2023-08-29 17:31
@ZeDima unfortunately I changed over to a manual install in a jail...

**Comment by ootagoo** [comment] 2023-08-29 17:45
> @ZeDima unfortunately I changed over to a manual install in a jail...

You can use the method I posted above to manually downgrade from inside the jail instead of rolling the whole jail back. But I guess for now we all just disable whatever automation we use to call PMS and wait for Plex devs to fix the issue.

**Comment by flipityflop** [comment] 2023-08-29 17:47
Does anyone know if the Plex devs actually know about this? Cause I didn't see anything on the support site, but I could've missed it

**Comment by MAGICCC** [comment] 2023-08-29 18:48
Well there's https://forums.plex.tv/t/plexmediaserver-1-32-6-7371-broken-on-freebsd/849348/38

**Comment by IrocDL** [comment] 2023-08-29 19:00
Lol so they haven’t even acknowledged it. Priceless.

**Comment by flipityflop** [comment] 2023-08-29 19:49
Plex forums are a mess, they don't really moderate or acknowledge things unless it somehow gets the attention of a dev, who might pop in and ask for logs and then never be heard from again

**Comment by IrocDL** [comment] 2023-08-29 20:46
Lovely. Maybe I ought to rethink my Plex Pass subscription, especially
considering I don’t really use any of the features it provides….

**Comment by MAGICCC** [comment] 2023-09-04 18:37
Seems to be fixed now

**Closed by MAGICCC** 2023-09-04 18:37 UTC
